# fly.toml app configuration file generated for selfieleague on 2023-08-05T12:48:58-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "draftordie"
primary_region = "sea"
console_command = "/rails/bin/rails console"
kill_signal = "SIGINT"
kill_timeout = 5
swap_size_mb = 256

[processes]
  app = "./bin/rails server"
  worker = "bundle exec sidekiq"

[http_service]
  processes = ["app"]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  [http_service.concurrency]
    type = "requests"
    soft_limit = 200
    hard_limit = 250
  [[http_service.checks]]
    grace_period = "10s"
    interval = "60s"
    method = "GET"
    timeout = "10s"
    path = "/"

[[statics]]
  guest_path = "/rails/public"
  url_prefix = "/"

[env]
  LANG = "en_US.UTF-8"
  LOG_LEVEL = "warn"
  RACK_ENV = "production"
  RAILS_ENV = "production"
  RAILS_MAX_THREADS = "5"
  WEB_CONCURRENCY = "0"
  RAILS_LOG_TO_STDOUT = "true"
  RAILS_SERVE_STATIC_FILES = "true"

[deploy]
  release_command = "./bin/rails db:prepare"

[experimental]
  allowed_public_ports = []
  auto_rollback = true
